apiVersion: batch/v1
kind: Job
metadata:
  name: create-channel-artifacts
spec:
  template:
    spec:
      containers:
        - name: channel-generator
          image: hyperledger/fabric-tools:2.3
          workingDir: /
          command:
            - /bin/bash
            - -c
            - |
              set -e

              CHANNEL_NAME="mychannel"
              DELAY="3"
              MAX_RETRY="5"
              VERBOSE="true"
              export FABRIC_CFG_PATH=${PWD}/configtx

              createChannelTx() {
                set -x
                configtxgen -profile TwoOrgsChannel \
                  -outputCreateChannelTx ./channel-artifacts/${CHANNEL_NAME}.tx \
                  -channelID $CHANNEL_NAME
                res=$?
                { set +x; } 2>/dev/null
                if [ $res -ne 0 ]; then
                  echo "❌ Failed to generate channel configuration transaction"
                  exit 1
                fi
              }

              createAnchorPeerTx() {
                for orgmsp in Org1MSP Org2MSP Org3MSP; do
                  echo "Generating anchor peer update transaction for ${orgmsp}"
                  set -x
                  configtxgen -profile TwoOrgsChannel \
                    -outputAnchorPeersUpdate ./channel-artifacts/${orgmsp}anchors.tx \
                    -channelID $CHANNEL_NAME \
                    -asOrg ${orgmsp}
                  res=$?
                  { set +x; } 2>/dev/null
                  if [ $res -ne 0 ]; then
                    echo "❌ Failed to generate anchor peer update for ${orgmsp}"
                    exit 1
                  fi
                done
              }

              echo "📦 Generating channel creation transaction"
              createChannelTx

              echo "📦 Generating anchor peer update transactions"
              createAnchorPeerTx

              echo "✅ Done generating channel artifacts"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
      restartPolicy: Never
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: nfs-pvc