apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-orderer
spec:
  selector:
    matchLabels:
      app: ca-orderer
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-orderer
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:

        - name: ca-orderer
          image: hyperledger/fabric-ca:latest
          imagePullPolicy: "IfNotPresent"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw","--port","10054", "-d"
            ]
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          env:
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-orderer
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          - name: FABRIC_CA_SERVER_BOOTSTRAP_USER
            value: admin
          - name: FABRIC_CA_SERVER_BOOTSTRAP_PASSWORD
            value: adminpw
          - name: FABRIC_CA_SERVER_CSR_CN
            value: ca-orderer
          - name: FABRIC_CA_SERVER_CSR_HOSTS
            value: ca-orderer,localhost
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/ordererOrg