apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-org2-identities
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fabric-ca-client
          image: hyperledger/fabric-ca:1.4.9
          command:
            - /bin/sh
            - -c
            - |
              set -x

              mkdir -p /organizations/peerOrganizations/org2.example.com
              export FABRIC_CA_CLIENT_HOME=/organizations/peerOrganizations/org2.example.com

              # Enroll admin
              fabric-ca-client enroll -u https://admin:adminpw@ca-org2:8054 \
                --caname ca-org2 \
                --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              # Write NodeOUs config
              mkdir -p /organizations/peerOrganizations/org2.example.com/msp
              cat <<EOF > /organizations/peerOrganizations/org2.example.com/msp/config.yaml
              NodeOUs:
                Enable: true
                ClientOUIdentifier:
                  Certificate: cacerts/ca-org2-8054-ca-org2.pem
                  OrganizationalUnitIdentifier: client
                PeerOUIdentifier:
                  Certificate: cacerts/ca-org2-8054-ca-org2.pem
                  OrganizationalUnitIdentifier: peer
                AdminOUIdentifier:
                  Certificate: cacerts/ca-org2-8054-ca-org2.pem
                  OrganizationalUnitIdentifier: admin
                OrdererOUIdentifier:
                  Certificate: cacerts/ca-org2-8054-ca-org2.pem
                  OrganizationalUnitIdentifier: orderer
              EOF

              # Register peer0, user1, and admin
              fabric-ca-client register --caname ca-org2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem
              fabric-ca-client register --caname ca-org2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem
              fabric-ca-client register --caname ca-org2 --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              # Enroll peer0
              fabric-ca-client enroll -u https://peer0:peer0pw@ca-org2:8054 \
                --caname ca-org2 \
                -M /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp \
                --csr.hosts peer0.org2.example.com \
                --csr.hosts peer0-org2 \
                --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              cp /organizations/peerOrganizations/org2.example.com/msp/config.yaml \
                 /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/config.yaml

              # Enroll peer0 TLS
              fabric-ca-client enroll -u https://peer0:peer0pw@ca-org2:8054 \
                --caname ca-org2 \
                -M /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls \
                --enrollment.profile tls \
                --csr.hosts peer0.org2.example.com \
                --csr.hosts peer0-org2 \
                --csr.hosts ca-org2 \
                --csr.hosts localhost \
                --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/* \
                 /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/signcerts/* \
                 /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/keystore/* \
                 /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.key

              mkdir -p /organizations/peerOrganizations/org2.example.com/msp/tlscacerts
              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/* \
                 /organizations/peerOrganizations/org2.example.com/msp/tlscacerts/ca.crt

              mkdir -p /organizations/peerOrganizations/org2.example.com/tlsca
              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/* \
                 /organizations/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

              mkdir -p /organizations/peerOrganizations/org2.example.com/ca
              cp /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/cacerts/* \
                 /organizations/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem

              # Enroll user1
              fabric-ca-client enroll -u https://user1:user1pw@ca-org2:8054 \
                --caname ca-org2 \
                -M /organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp \
                --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              cp /organizations/peerOrganizations/org2.example.com/msp/config.yaml \
                 /organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/config.yaml

              # Enroll org2 admin
              fabric-ca-client enroll -u https://org2admin:org2adminpw@ca-org2:8054 \
                --caname ca-org2 \
                -M /organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp \
                --tls.certfiles /organizations/fabric-ca/org2/tls-cert.pem

              cp /organizations/peerOrganizations/org2.example.com/msp/config.yaml \
                 /organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/config.yaml
          volumeMounts:
            - name: orgdata
              mountPath: /organizations
              subPath: organizations
      volumes:
        - name: orgdata
          persistentVolumeClaim:
            claimName: nfs-pvc